import { mutation } from "./_generated/server";

export const seed = mutation({
  args: {},
  handler: async (ctx) => {
    // Check if data already exists
    const existing = await ctx.db.query("medicines").first();
    if (existing) {
      return { message: "Data already seeded" };
    }

    // Comprehensive seed sample medicines
    const medicines = [
      // Pain Relief & Fever
      {
        code: "MED001234",
        name: "Paracetamol 500mg",
        manufacturer: "PharmaCorp Ltd.",
        batchNo: "PC2024-A156",
        mfgDate: "2024-03-15",
        expDate: "2026-03-14",
        licenseNo: "DL-12345",
        status: "legal" as const,
        country: "India",
        composition: "Paracetamol 500mg",
        warnings: [],
      },
      {
        code: "MED002468",
        name: "Ibuprofen 400mg",
        manufacturer: "HealthPlus Industries",
        batchNo: "HP2024-C234",
        mfgDate: "2024-01-10",
        expDate: "2026-01-09",
        licenseNo: "DL-24680",
        status: "recalled" as const,
        country: "India",
        composition: "Ibuprofen 400mg",
        warnings: ["Product recalled due to quality concerns", "Return to pharmacy"],
      },
      {
        code: "MED010101",
        name: "Aspirin 75mg",
        manufacturer: "CardioMed Pharma",
        batchNo: "CM2024-D789",
        mfgDate: "2024-02-20",
        expDate: "2026-02-19",
        licenseNo: "DL-10101",
        status: "legal" as const,
        country: "India",
        composition: "Acetylsalicylic Acid 75mg",
        warnings: ["Not for children under 16"],
      },
      {
        code: "MED010202",
        name: "Diclofenac Sodium 50mg",
        manufacturer: "PainRelief Inc.",
        batchNo: "PR2023-E456",
        mfgDate: "2023-08-15",
        expDate: "2024-08-14",
        licenseNo: "DL-10202",
        status: "expired" as const,
        country: "India",
        composition: "Diclofenac Sodium 50mg",
        warnings: ["Expired - Do not use"],
      },

      // Antibiotics
      {
        code: "MED005678",
        name: "Amoxicillin 250mg",
        manufacturer: "MediLife Pharma",
        batchNo: "ML2023-B892",
        mfgDate: "2023-06-20",
        expDate: "2024-06-19",
        licenseNo: "DL-67890",
        status: "expired" as const,
        country: "India",
        composition: "Amoxicillin Trihydrate 250mg",
        warnings: ["Expired - Do not use"],
      },
      {
        code: "MED020301",
        name: "Azithromycin 500mg",
        manufacturer: "AntiBio Labs",
        batchNo: "AB2024-F123",
        mfgDate: "2024-04-10",
        expDate: "2026-04-09",
        licenseNo: "DL-20301",
        status: "legal" as const,
        country: "India",
        composition: "Azithromycin Dihydrate 500mg",
        warnings: ["Complete full course as prescribed"],
      },
      {
        code: "MED020302",
        name: "Ciprofloxacin 500mg",
        manufacturer: "BioMed Solutions",
        batchNo: "BM2024-G456",
        mfgDate: "2024-03-25",
        expDate: "2026-03-24",
        licenseNo: "DL-20302",
        status: "legal" as const,
        country: "India",
        composition: "Ciprofloxacin Hydrochloride 500mg",
        warnings: ["Avoid dairy products within 2 hours"],
      },
      {
        code: "MED020303",
        name: "Cephalexin 500mg",
        manufacturer: "GeneriCare Pharma",
        batchNo: "GC2024-H789",
        mfgDate: "2024-01-15",
        expDate: "2026-01-14",
        licenseNo: "DL-20303",
        status: "legal" as const,
        country: "India",
        composition: "Cephalexin 500mg",
        warnings: [],
      },

      // Allergy & Cold
      {
        code: "MED003579",
        name: "Cetirizine 10mg",
        manufacturer: "AllerCare Pharmaceuticals",
        batchNo: "AC2024-D567",
        mfgDate: "2024-02-28",
        expDate: "2026-02-27",
        licenseNo: "DL-35790",
        status: "legal" as const,
        country: "India",
        composition: "Cetirizine Hydrochloride 10mg",
        warnings: [],
      },
      {
        code: "MED030401",
        name: "Loratadine 10mg",
        manufacturer: "AllergyFree Labs",
        batchNo: "AF2024-I234",
        mfgDate: "2024-03-10",
        expDate: "2026-03-09",
        licenseNo: "DL-30401",
        status: "legal" as const,
        country: "India",
        composition: "Loratadine 10mg",
        warnings: [],
      },
      {
        code: "MED030402",
        name: "Pseudoephedrine 60mg",
        manufacturer: "ColdCure Pharma",
        batchNo: "CC2023-J567",
        mfgDate: "2023-11-20",
        expDate: "2024-11-19",
        licenseNo: "DL-30402",
        status: "expired" as const,
        country: "India",
        composition: "Pseudoephedrine Hydrochloride 60mg",
        warnings: ["Expired - Do not use"],
      },

      // Diabetes Management
      {
        code: "MED040501",
        name: "Metformin 500mg",
        manufacturer: "DiabetoCare Inc.",
        batchNo: "DC2024-K890",
        mfgDate: "2024-04-05",
        expDate: "2026-04-04",
        licenseNo: "DL-40501",
        status: "legal" as const,
        country: "India",
        composition: "Metformin Hydrochloride 500mg",
        warnings: ["Take with meals"],
      },
      {
        code: "MED040502",
        name: "Glimepiride 2mg",
        manufacturer: "SugarControl Pharma",
        batchNo: "SC2024-L123",
        mfgDate: "2024-02-15",
        expDate: "2026-02-14",
        licenseNo: "DL-40502",
        status: "legal" as const,
        country: "India",
        composition: "Glimepiride 2mg",
        warnings: ["Monitor blood sugar regularly"],
      },

      // Cardiovascular
      {
        code: "MED050601",
        name: "Atorvastatin 10mg",
        manufacturer: "HeartHealth Labs",
        batchNo: "HH2024-M456",
        mfgDate: "2024-03-20",
        expDate: "2026-03-19",
        licenseNo: "DL-50601",
        status: "legal" as const,
        country: "India",
        composition: "Atorvastatin Calcium 10mg",
        warnings: ["Avoid grapefruit juice"],
      },
      {
        code: "MED050602",
        name: "Amlodipine 5mg",
        manufacturer: "BPControl Pharma",
        batchNo: "BP2024-N789",
        mfgDate: "2024-01-25",
        expDate: "2026-01-24",
        licenseNo: "DL-50602",
        status: "legal" as const,
        country: "India",
        composition: "Amlodipine Besylate 5mg",
        warnings: [],
      },
      {
        code: "MED050603",
        name: "Losartan 50mg",
        manufacturer: "CardioVascular Inc.",
        batchNo: "CV2024-O012",
        mfgDate: "2024-04-01",
        expDate: "2026-03-31",
        licenseNo: "DL-50603",
        status: "legal" as const,
        country: "India",
        composition: "Losartan Potassium 50mg",
        warnings: ["Monitor blood pressure regularly"],
      },

      // Gastrointestinal
      {
        code: "MED060701",
        name: "Omeprazole 20mg",
        manufacturer: "GastroRelief Pharma",
        batchNo: "GR2024-P345",
        mfgDate: "2024-02-10",
        expDate: "2026-02-09",
        licenseNo: "DL-60701",
        status: "legal" as const,
        country: "India",
        composition: "Omeprazole 20mg",
        warnings: ["Take before meals"],
      },
      {
        code: "MED060702",
        name: "Ranitidine 150mg",
        manufacturer: "AcidControl Labs",
        batchNo: "AC2023-Q678",
        mfgDate: "2023-09-15",
        expDate: "2024-09-14",
        licenseNo: "DL-60702",
        status: "recalled" as const,
        country: "India",
        composition: "Ranitidine Hydrochloride 150mg",
        warnings: ["Product recalled - potential contamination", "Return immediately"],
      },
      {
        code: "MED060703",
        name: "Loperamide 2mg",
        manufacturer: "DigestCare Pharma",
        batchNo: "DP2024-R901",
        mfgDate: "2024-03-05",
        expDate: "2026-03-04",
        licenseNo: "DL-60703",
        status: "legal" as const,
        country: "India",
        composition: "Loperamide Hydrochloride 2mg",
        warnings: ["Do not exceed recommended dose"],
      },

      // Vitamins & Supplements
      {
        code: "MED070801",
        name: "Vitamin D3 1000IU",
        manufacturer: "NutriHealth Labs",
        batchNo: "NH2024-S234",
        mfgDate: "2024-01-20",
        expDate: "2026-01-19",
        licenseNo: "DL-70801",
        status: "legal" as const,
        country: "India",
        composition: "Cholecalciferol 1000IU",
        warnings: [],
      },
      {
        code: "MED070802",
        name: "Calcium Carbonate 500mg",
        manufacturer: "BoneStrong Pharma",
        batchNo: "BS2024-T567",
        mfgDate: "2024-02-25",
        expDate: "2026-02-24",
        licenseNo: "DL-70802",
        status: "legal" as const,
        country: "India",
        composition: "Calcium Carbonate 500mg + Vitamin D3 250IU",
        warnings: [],
      },
      {
        code: "MED070803",
        name: "Multivitamin Complex",
        manufacturer: "VitaLife Inc.",
        batchNo: "VL2024-U890",
        mfgDate: "2024-03-15",
        expDate: "2026-03-14",
        licenseNo: "DL-70803",
        status: "legal" as const,
        country: "India",
        composition: "Multivitamin & Mineral Complex",
        warnings: [],
      },

      // Counterfeit Examples
      {
        code: "MED009999",
        name: "Fake Aspirin",
        manufacturer: "Unknown Source",
        batchNo: "FAKE-001",
        mfgDate: "2024-01-01",
        expDate: "2025-01-01",
        licenseNo: "INVALID",
        status: "counterfeit" as const,
        country: "Unknown",
        composition: "Unknown substances",
        warnings: ["COUNTERFEIT DETECTED", "Do not consume", "Report immediately"],
      },
      {
        code: "MED009998",
        name: "Counterfeit Viagra",
        manufacturer: "Illegal Manufacturer",
        batchNo: "FAKE-002",
        mfgDate: "2024-02-01",
        expDate: "2025-02-01",
        licenseNo: "INVALID",
        status: "counterfeit" as const,
        country: "Unknown",
        composition: "Unknown - potentially dangerous",
        warnings: ["COUNTERFEIT DETECTED", "Contains harmful substances", "Report to authorities"],
      },
      {
        code: "MED009997",
        name: "Fake Antibiotic",
        manufacturer: "Unverified Source",
        batchNo: "FAKE-003",
        mfgDate: "2024-03-01",
        expDate: "2025-03-01",
        licenseNo: "INVALID",
        status: "counterfeit" as const,
        country: "Unknown",
        composition: "No active ingredients detected",
        warnings: ["COUNTERFEIT DETECTED", "Ineffective treatment", "Seek genuine medicine immediately"],
      },

      // Mental Health
      {
        code: "MED080901",
        name: "Sertraline 50mg",
        manufacturer: "MindCare Pharma",
        batchNo: "MC2024-V123",
        mfgDate: "2024-04-15",
        expDate: "2026-04-14",
        licenseNo: "DL-80901",
        status: "legal" as const,
        country: "India",
        composition: "Sertraline Hydrochloride 50mg",
        warnings: ["Prescription only", "Do not stop abruptly"],
      },
      {
        code: "MED080902",
        name: "Alprazolam 0.5mg",
        manufacturer: "AnxietyRelief Labs",
        batchNo: "AR2024-W456",
        mfgDate: "2024-03-30",
        expDate: "2026-03-29",
        licenseNo: "DL-80902",
        status: "legal" as const,
        country: "India",
        composition: "Alprazolam 0.5mg",
        warnings: ["Controlled substance", "May cause drowsiness", "No alcohol"],
      },

      // Respiratory
      {
        code: "MED091001",
        name: "Salbutamol Inhaler",
        manufacturer: "BreathEasy Pharma",
        batchNo: "BE2024-X789",
        mfgDate: "2024-02-05",
        expDate: "2026-02-04",
        licenseNo: "DL-91001",
        status: "legal" as const,
        country: "India",
        composition: "Salbutamol 100mcg per dose",
        warnings: ["Shake well before use"],
      },
      {
        code: "MED091002",
        name: "Montelukast 10mg",
        manufacturer: "AsthmaControl Inc.",
        batchNo: "AC2024-Y012",
        mfgDate: "2024-01-10",
        expDate: "2026-01-09",
        licenseNo: "DL-91002",
        status: "legal" as const,
        country: "India",
        composition: "Montelukast Sodium 10mg",
        warnings: ["Take in the evening"],
      },
    ];

    for (const medicine of medicines) {
      await ctx.db.insert("medicines", medicine);
    }

    return { message: `Successfully seeded ${medicines.length} medicines` };
  },
});